// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.31.1
// source: gifting-service/proto/gifting.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GiftingServiceClient is the client API for GiftingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GiftingServiceClient interface {
	// Mengirim hadiah buku dari donor ke penerima
	SendGift(ctx context.Context, in *SendGiftRequest, opts ...grpc.CallOption) (*SendGiftResponse, error)
}

type giftingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGiftingServiceClient(cc grpc.ClientConnInterface) GiftingServiceClient {
	return &giftingServiceClient{cc}
}

func (c *giftingServiceClient) SendGift(ctx context.Context, in *SendGiftRequest, opts ...grpc.CallOption) (*SendGiftResponse, error) {
	out := new(SendGiftResponse)
	err := c.cc.Invoke(ctx, "/gifting.GiftingService/SendGift", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GiftingServiceServer is the server API for GiftingService service.
// All implementations must embed UnimplementedGiftingServiceServer
// for forward compatibility
type GiftingServiceServer interface {
	// Mengirim hadiah buku dari donor ke penerima
	SendGift(context.Context, *SendGiftRequest) (*SendGiftResponse, error)
	mustEmbedUnimplementedGiftingServiceServer()
}

// UnimplementedGiftingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGiftingServiceServer struct {
}

func (UnimplementedGiftingServiceServer) SendGift(context.Context, *SendGiftRequest) (*SendGiftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGift not implemented")
}
func (UnimplementedGiftingServiceServer) mustEmbedUnimplementedGiftingServiceServer() {}

// UnsafeGiftingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GiftingServiceServer will
// result in compilation errors.
type UnsafeGiftingServiceServer interface {
	mustEmbedUnimplementedGiftingServiceServer()
}

func RegisterGiftingServiceServer(s grpc.ServiceRegistrar, srv GiftingServiceServer) {
	s.RegisterService(&GiftingService_ServiceDesc, srv)
}

func _GiftingService_SendGift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftingServiceServer).SendGift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gifting.GiftingService/SendGift",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftingServiceServer).SendGift(ctx, req.(*SendGiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GiftingService_ServiceDesc is the grpc.ServiceDesc for GiftingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GiftingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gifting.GiftingService",
	HandlerType: (*GiftingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendGift",
			Handler:    _GiftingService_SendGift_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gifting-service/proto/gifting.proto",
}
